### ISSUE TITLE
Backend discussion of Notification system

### ISSUE THREAD

**Issue by sadiuysal** [bounswe/bounswe2020group9#272]
Please discuss and get help about the notification structure for the vendor and customer side with the backend as soon as possible.

**Comment by mehmetkemaloglu** [comment]
Today, I started to working on it. We planned the structure will be same for both vendor and customer. They both have notification however, the notification types will not be same. The contents of the notifications are order and change of the status of order. 

There will be GET and POST request. GET request will respond all notifications and the number of the unseen notifications. POST request will change the unseen status of the all notifications to the seen status.

My current plan is implementing the following API. It is still changeable because we didn't finish the order structure. Of course I'm open to other ideas.

Example GET response:
{
  "unseen": 1,
  "notifications": 
   [
     {
       "id": 4
       "user": 12,
       "body": "example body",
       "timestamp": "time",
       "type": "order",
       "is_visited": False
     }
     ...more notifications
  ]
}

**Comment by sadiuysal** [comment]
I think we can add related_order_id field for reaching notification related orders.

**Comment by sadiuysal** [comment]
Discussion is made. Implementation is done. Closing issue.
